# Generated by Django 6.0.5 on 2026-05-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_email', models.EmailField(max_length=254)),
                ('donor_wallet', models.CharField(max_length=100)),
                ('tokens_minted', models.PositiveIntegerField()),
                ('bag_id', models.CharField(max_length=100)),
                ('tx_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
