# Generated by Django 4.2.29 on 2026-05-05 03:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodBag',
            fields=[
                ('bag_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('status', models.CharField(choices=[('collected', 'collected'), ('tested', 'tested'), ('stored', 'stored'), ('transfused', 'transfused'), ('expired', 'expired')], default='collected', max_length=20)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('blockchain_tx_hash', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
